<?php
/**
 * PAYONE OXID Connector is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PAYONE OXID Connector is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with PAYONE OXID Connector.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.payone.de
 * @copyright (C) Payone GmbH
 * @version   OXID eShop CE
 */


$sLangName = "English";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset'                                   => 'UTF-8',
    'fcpo_admin_title'                          => 'PAYONE',
    'fcpo_main_title'                           => 'PAYONE Configuration',
    'fcpo_main_log'                             => 'PAYONE Transactions',
    'FCPO_MERCHANT_ID'                          => 'PAYONE Merchant ID',
    'FCPO_PORTAL_ID'                            => 'PAYONE Portal ID',
    'FCPO_PORTAL_KEY'                           => 'PAYONE Portal Key',
    'FCPO_OPERATION_MODE'                       => 'PAYONE Operation mode',
    'FCPO_SUBACCOUNT_ID'                        => 'PAYONE Sub-Account ID',
    'FCPO_LIVE_MODE'                            => 'Live mode',
    'FCPO_TEST_MODE'                            => 'Test mode',
    'fcpo_order_title'                          => 'PAYONE',
    'FCPO_REFNR'                                => 'Reference number',
    'FCPO_TXID'                                 => 'PAYONE-Transaction Number (txid)',
    'fcpo_action_appointed'                     => 'Order',
    'fcpo_action_capture'                       => 'Capture',
    'fcpo_action_paid'                          => 'Paid',
    'fcpo_action_underpaid'                     => 'Underpaid',
    'fcpo_action_overpaid'                      => '<span style="color: red;">Overpaid</span>',
    'fcpo_action_cancelation'                   => 'Cancellation',
    'fcpo_action_refund'                        => 'Refund',
    'fcpo_action_debit'                         => 'Demand/Credit',
    'fcpo_action_transfer'                      => 'Transfer',
    'fcpo_action_reminder'                      => 'State dunning',
    'fcpo_clearingtype_elv'                     => 'Direct Debit',
    'fcpo_clearingtype_cc'                      => 'Credit Card',
    'fcpo_clearingtype_vor'                     => 'Payadvance',
    'fcpo_clearingtype_rec'                     => 'Bill',
    'fcpo_clearingtype_cod'                     => 'Cash on delivery',
    'fcpo_clearingtype_sb'                      => 'Online-Transfer',
    'fcpo_clearingtype_wlt'                     => 'e-Wallet',
    'fcpo_clearingtype_fnc'                     => 'Financing',
    'fcpo_clearingtype_csh'                     => 'Barzahlen',
    'fcpo_clearingtype_fcpoklarna'              => 'Klarna Invoice',
    'fcpo_clearingtype_fcpoklarna_invoice'      => 'Klarna pay later',
    'fcpo_clearingtype_fcpoklarna_installments' => 'Klarna slice it',
    'fcpo_clearingtype_fcpoklarna_directdebit'  => 'Klarna pay now',
    'fcpo_clearingtype_fcpopo_bill'             => 'Unzer Invoice',
    'fcpo_clearingtype_fcpopo_debitnote'        => 'Unzer Debit',
    'fcpo_clearingtype_fcpopo_installment'      => 'Unzer Installment',
    'fcpo_clearingtype_fcporp_debitnote'        => 'Ratepay Debit',
    'fcpo_clearingtype_fcporp_bill'             => 'Ratepay Invoice',
    'fcpo_clearingtype_fcporp_installment'      => 'Ratepay Installment',
    'fcpo_clearingtype_fcpopl_secinvoice'       => 'BNPL Secured Invoice',
    'fcpo_clearingtype_fcpopl_secinstallment'   => 'BNPL Secured Installment',
    'fcpo_clearingtype_fcpopl_secdebitnote'     => 'BNPL Secured Direct Debit',
    'FCPO_CAPTURE_APPROVED'                     => 'Booking was successfull',
    'FCPO_CAPTURE_ERROR'                        => 'Error occured during booking: ',
    'FCPO_DEBIT_APPROVED'                       => 'Credit was successfull',
    'FCPO_DEBIT_ERROR'                          => 'Error occured during credit: ',
    'FCPO_AMOUNT_IN'                            => 'Amount in',
    'FCPO_LIST_HEADER_TITLE'                    => 'Transaction account',
    'FCPO_LIST_HEADER_TXTIME'                   => 'Timestamp',
    'FCPO_LIST_HEADER_PROCESS'                  => 'Process',
    'FCPO_LIST_HEADER_DEMAND'                   => 'Demand',
    'FCPO_LIST_HEADER_ORDERNR'                  => 'Order Nr.',
    'FCPO_LIST_HEADER_TXID'                     => 'Transaction number',
    'FCPO_LIST_HEADER_CLEARINGTYPE'             => 'Payment method',
    'FCPO_LIST_HEADER_EMAIL'                    => 'Customer e-mail',
    'FCPO_LIST_HEADER_PRICE'                    => 'Price amount',
    'FCPO_LIST_HEADER_TXACTION'                 => 'State',
    'FCPO_LIST_HEADER_FORWARD_STATE'            => 'Forward State',
    'FCPO_LIST_HEADER_FORWARD_TRIES'            => 'Forward Tries',
    'FCPO_EXECUTE'                              => 'Execute',
    'FCPO_CAPTURE'                              => 'Capture ',
    'FCPO_DEBIT'                                => 'Debit ',
    'FCPO_ARE_YOU_SURE'                         => 'Are you sure that you want to perform this action?',
    'FCPO_DE'                                   => 'Germany',
    'FCPO_AT'                                   => 'Austria',
    'FCPO_NL'                                   => 'Netherlands',
    'FCPO_HEADER_BANKACCOUNT'                   => 'Bankaccount (optional)',
    'FCPO_BANKCOUNTRY'                          => 'Account country',
    'FCPO_BANKACCOUNT'                          => 'Account number',
    'FCPO_BANKCODE'                             => 'Bank code number',
    'FCPO_BANKACCOUNTHOLDER'                    => 'Account owner',
    'FCPO_SHOW'                                 => 'show',
    'FCPO_HIDE'                                 => 'hide',
    'FCPO_PAYMENTTYPE'                          => 'Payment type',
    'FCPO_CARDEXPIREDATE'                       => 'Expiredate',
    'FCPO_CARDTYPE'                             => 'Card type',
    'FCPO_CARDPAN'                              => 'Masked Card Number',
    'FCPO_BALANCE'                              => 'Balance',
    'FCPO_RECEIVABLE'                           => 'Payment',
    'FCPO_NO_TRANSACTION_STATUS_RECEIVED'       => 'No transaction status received.',
    'FC_IS_PAYONE'                              => 'This is a PAYONE payment method',
    'FCPO_HELP_MERCHANTID'                      => 'You will find your PAYONE Merchant-ID on each invoice of PAYONE as well as on the right upper corner of the PAYONE Merchant Interface (PMI).',
    'FCPO_HELP_PORTALID'                        => 'Please enter PAYONE Portal-ID which is used to complete payments.<br>You will find your Portal-ID at <a href="http://www.payone.de" target="_blank">http://www.payone.de</a> > Merchant-Login at menu entry Configuration > Payment Portals<br><br>You will get all relevant configuration parameters [edit] under tab [API-Parameter]',
    'FCPO_HELP_PORTALKEY'                       => 'Please enter the Key that is used for secure transaction . This can be freely configured by you in PAYONE Portal interface.<br>You can find this configuration at <a href="http://www.payone.de" target="_blank">http://www.payone.de</a> > Merchant-Login at menu entry Configuration > Payment Portals > [editieren] > Reiter [Erweitert] > Key<br><br>You will get all relevant configuration parameters under tab [API-Parameter]',
    'FCPO_HELP_OPERATIONMODE'                   => 'Here you can configure if the payments are processed in test mode, or whether they are performed live. Please note that for using the test mode, usage of defined test data si required.',
    'FCPO_HELP_SUBACCOUNTID'                    => 'Please enter the ID of the Sub-Account, which will be processed through the payments and allocated. <br> The ID can be found at <a href = "http://www.payone.de" target = "_blank" > http://www.payone.de </ a>> Merchant Login in the menu Settings> Accounts <br> All relevant parameters for configuration, please visit <a href = "http://www.payone . de [edit] "target =" _blank "> http://www.payone.de </ a>> Merchant Login in the menu configuration> Payment portals>> tab [API parameters]',
    'fcpo_admin_config'                         => 'PAYONE Configuration',
    'fcpo_admin_config_payment'                 => 'PAYONE Payment Settings',
    'fcpo_admin_protocol'                       => 'PAYONE Protocols / Logs',
    'FCPO_NO_TRANSACTION'                       => 'No transaction selected',
    'fcpo_admin_information'                    => 'PAYONE Information',
    'fcpo_admin_common'                         => 'General',
    'fcpo_admin_support'                        => 'Support',
    'fcpo_admin_api_logs'                       => 'API Logs',
    'FCPO_LIST_HEADER_TIMESTAMP'                => 'Time',
    'FCPO_LIST_HEADER_REQUEST'                  => 'Request',
    'FCPO_LIST_HEADER_RESPONSE'                 => 'Response',
    'FCPO_NO_APILOG'                            => 'No log entry selected',
    'FCPO_ACTIVE_CREDITCARD_TYPES'              => 'Active credit card brands',
    'FCPO_CREDITCARDBRANDS_INFOTEXT'            => 'Here, the individual credit card brands, for the payment method to enable and configure credit card & Returns Please note that were the respective credit card brand in PAYONE charge must be <br> The setting for the payment by credit card you take with PAYONE -> Configuration -> payment before.',
    'FCPO_ACTIVE_ONLINE_UBERWEISUNG_TYPES'      => 'Active online payment types',
    'FCPO_ONLINEUBERWEISUNG_INFOTEXT'           => 'Here you can enable/disable the individual types of online money transfer and are able to configure the online payments as well as referral. <br> Please note that these payment methods have to be ordered individually before. <br> The settings for accepting online transfers in PAYONE  can be found at PAYONE -> Configuration -> payment types in the PAYONE merchant interface.',
    'FCPO_CHANNEL'                              => 'Channel',
    'FCPO_AUTHORIZATION_METHOD'                 => 'Authorize-Method',
    'FCPO_PREAUTHORIZATION'                     => 'Preauthorization',
    'FCPO_PREAUTHORIZATION_HELP'                => 'When you select "Preauthorization" the payable amount will be reserved as part of the order [recommended by PAYONE]. The charge (capture) must be initiated in a second step in before delivering the goods.',
    'FCPO_AUTHORIZATION'                        => 'Authorize',
    'FCPO_AUTHORIZATION_HELP'                   => 'When choosing "authorization", the amount to be paid will be charged immediately during the order.',
    'dyn_fcpayone'                              => 'PAYONE',
    'FCPO_ONLY_PAYONE'                          => 'PAYONE Payment Methods only',
    'ORDER_LIST_YOUWANTTOSTORNO'                => 'Do you really want to cancel this order?\n CAUTION: Eventually open PAYONE transactions should be completed before performing this action.',
    'FCPO_ORDER_LIST_YOUWANTTODELETE'           => 'Do you really want to delete this order?\n \n CAUTION: Eventually open PAYONE transactions should be completed before deleting this order.',
    'FCPO_SEND_ARTICLELIST'                     => 'Send article list',
    'FCPO_HELP_SEND_ARTICLELIST'                => 'When activated the proposed requests will be sent to the system of PAYONE including the individual prices of items shipped. <br> This option must be checked if they have activated the PAYONE invoicing.',
    'FCPO_STATUS_WITH_USER_CORRECTION'          => 'User will be sent back to user form, if:',
    'FCPO_MODULE_VERSION'                       => 'Module Version',
    'FCPO_HELP_ASSIGNCOUNTRIES'                 => 'If no countries are assigned, the payment applies to all countries. <br> If countries are assigned, the payment applies only to these countries. <br> Billing country and destination country weill be tested.',
    'fcpo_receivable_appointed1'                => 'Reservation',
    'fcpo_receivable_appointed2'                => 'Demand (Authorazation)',
    'fcpo_receivable_capture'                   => 'Demand (Capture)',
    'fcpo_receivable_debit1'                    => 'Demand (Debit)',
    'fcpo_receivable_debit2'                    => 'Credit (Debit/Refund)',
    'fcpo_receivable_reminder'                  => 'Reminder delivery',
    'fcpo_receivable_cancelation'               => 'Chargeback fee',
    'fcpo_payment_capture1'                     => 'Indent',
    'fcpo_payment_capture2'                     => 'Payout',
    'fcpo_payment_paid1'                        => 'Receipt of payment',
    'fcpo_payment_paid2'                        => 'Chargeback',
    'fcpo_payment_underpaid1'                   => 'Underpaid',
    'fcpo_payment_underpaid2'                   => 'Chargeback',
    'fcpo_payment_debit1'                       => 'Indent',
    'fcpo_payment_debit2'                       => 'Payout',
    'fcpo_payment_transfer'                     => 'Rebooking',
    'fcpo_payment'                              => 'Payment',
    'FCPO_MAIN_CONFIG_INFOTEXT'                 => 'You can configure individually for each payment type, whether it should be handled in test or live mode. You can set them at PAYONE -> Configuration -> Payment Methods. We recommend following the initial configuration in test mode and switch over to live mode if everything works as expected.',
    'FCPO_MAIN_CONFIG_TESTACCOUNT_LINK'         => 'Need a test account? Open a no obligation test account <a href="https://www.payone.com/DE-de/kampagne/ecom-testaccount" target="_blank">>>here<<</a>',
    'FCPO_INFOTEXT_SET_OPERATIONMODE'           => 'Will be set manually at PAYONE->Configuration->payment settings',
    'FCPO_SETTLE_ACCOUNT'                       => 'Perform settlement',
    'FCPO_HELP_SETTLE_ACCOUNT'                  => 'Disable checkbox for partial "Perform settlement" . Be activated during the last partial delivery has this option to perform a balancing accounts. Please note that this function only for ELV, in advance, online payment and billing is available. Also this feature for credit card prior to activation of PAYONE is available.',
    'FCPO_PRESAVE_ORDER'                        => 'Save order before authorization',
    'FCPO_REDUCE_STOCK'                         => 'Reduce stock',
    'FCPO_HELP_REDUCE_STOCK'                    => 'This configuration only has effect when "Save order before authorization" is activated and the customer is redirected to an external paymentservice ( i.e. Sofort�berweisung, PayPal or creditcard with 3D Secure ). This configuration defines if the stock for the articles is reduced before or after the redirect to the external paymentservice.',
    'FCPO_REDUCE_STOCK_BEFORE'                  => 'before authorization',
    'FCPO_REDUCE_STOCK_AFTER'                   => 'after authorization',
    'FCPO_HELP_PRESAVE_ORDER'                   => 'The order is saved before the authorization als incomplete Order, so that there is a order-number which can be sent to PAYONE.',
    'FCPO_VOUCHER'                              => 'voucher',
    'FCPO_DISCOUNT'                             => 'discount',
    'FCPO_WRAPPING'                             => "Gift Wrapping",
    'FCPO_GIFTCARD'                             => "Greeting Card",
    'FCPO_SURCHARGE'                            => 'Surcharge',
    'FCPO_DEDUCTION'                            => 'Deduction',
    'FCPO_SHIPPINGCOST'                         => "Shipping cost",
    'FCPO_PRODUCT_CAPTURE'                      => "Capture",
    'FCPO_PRODUCTS'                             => "Products",
    'FCPO_PRODUCT_AMOUNT'                       => "Amount",
    'FCPO_PRODUCT_PRICE'                        => "Unit price",
    'FCPO_PRODUCT_TITLE'                        => "Product",
    'FCPO_PRODUCT_TOTAL'                        => "Total",
    'FCPO_COMPLETE_ORDER'                       => "Complete order",
    'FCPO_ORDERNOTCHECKED'                      => "The customer did not accept the<br>consumerscore check for this order!",
    'fcpo_admin_config_status_forwarding'       => "Transactionsstatus - forwarding",
    'fcpo_admin_config_status_mapping'          => "Transactionsstatus - mapping",
    'fcpo_admin_config_error_mapping'           => "Errormessage - Mapping",
    'fcpo_admin_config_add'                     => "add",
    'fcpo_admin_config_delete'                  => "delete",
    'fcpo_admin_config_delete_confirm'          => "Do you really want to delete this entry?",
    'fcpo_admin_config_paymenttype'             => "payment-method",
    'fcpo_admin_config_status_payone'           => "PAYONE status",
    'fcpo_admin_config_status_shop'             => "shop - status",
    'fcpo_admin_config_status'                  => "status",
    'fcpo_admin_config_url'                     => "URL",
    'fcpo_admin_config_timeout'                 => "timeout",
    'fcpo_status_appointed'                     => "appointed",
    'fcpo_status_capture'                       => "capture",
    'fcpo_status_paid'                          => "paid",
    'fcpo_status_underpaid'                     => "underpaid",
    'fcpo_status_cancelation'                   => "cancelation",
    'fcpo_status_refund'                        => "refund",
    'fcpo_status_debit'                         => "debit",
    'fcpo_status_reminder'                      => "reminder",
    'fcpo_status_vauthorization'                => "vauthorization",
    'fcpo_status_vsettlement'                   => "vsettlement",
    'fcpo_status_transfer'                      => "transfer",
    'fcpo_status_invoice'                       => "invoice",

    'FCPO_CONFIG_GROUP_CONN'                    => "Connection-configuration",
    'FCPO_CONFIG_GROUP_GENERAL'                 => "General",
    'FCPO_CONFIG_GROUP_DEBITNOTE'               => "Debit",
    'FCPO_CONFIG_GROUP_CREDITCARD'              => "Creditcard",
    'FCPO_CONFIG_GROUP_PAYOLUTION'              => 'Payolution',
    'FCPO_CONFIG_GROUP_RATEPAY'                 => 'Ratepay',
    'FCPO_CONFIG_GROUP_AMAZONPAY'               => 'AmazonPay',
    'FCPO_AMAZONPAY_SELLERID'                   => 'Amazon Seller-ID',
    'FCPO_AMAZONPAY_CLIENTID'                   => 'Amazon Client-ID',
    'FCPO_AMAZONPAY_GET_CONFIG'                 => 'Retrieve Amazon-Configuration from PAYONE',
    'FCPO_AMAZONPAY_ERROR_GETTING_CONFIG'       => 'An error occurred retrieving configuration. Check API-Logs for further information.',
    'FCPO_AMAZONPAY_SUCCESS_GETTING_CONFIG'     => 'AmazonPay-Configuration successfully retrieved',
    'FCPO_AMAZONPAY_BUTTON_TYPE'                => 'Amazon Button Type',
    'FCPO_AMAZONPAY_BUTTON_TYPE_PwA'            => 'Amazon Pay (Standard)',
    'FCPO_AMAZONPAY_BUTTON_TYPE_Pay'            => 'Pay (smaller)',
    'FCPO_AMAZONPAY_BUTTON_TYPE_A'              => 'Amazon Logo (small)',
    'FCPO_AMAZONPAY_BUTTON_COLOR'               => 'Amazon Button Color',
    'FCPO_AMAZONPAY_BUTTON_COLOR_GOLD'          => 'Gold (standard)',
    'FCPO_AMAZONPAY_BUTTON_TYPE_LIGHT_GRAY'     => 'Light Grey',
    'FCPO_AMAZONPAY_BUTTON_TYPE_DARKGRAY'       => 'Dark grey',
    'FCPO_AMAZONPAY_BUTTON_LANG'                => 'Amazon Button Language',
    'FCPO_AMAZONPAY_BUTTON_LANG_NONE'           => 'automatically',
    'FCPO_AMAZONPAY_BUTTON_LANG_ENGLISH_UK'     => 'English (UK)',
    'FCPO_AMAZONPAY_BUTTON_LANG_GERMAN_GERMANY' => 'German (Germany)',
    'FCPO_AMAZONPAY_BUTTON_LANG_FRENCH_FRANCE'  => 'French (France)',
    'FCPO_AMAZONPAY_BUTTON_LANG_ITALIAN_ITALY'  => 'Italian (Italy)',
    'FCPO_AMAZONPAY_BUTTON_LANG_SPANISH_SPAIN'  => 'Spanish (Spain)',
    'FCPO_AMAZONPAY_MODE'                       => 'Amazon-Mode',
    'FCPO_AMAZONPAY_MODE_ALWAYSSYNC'            => 'Always synchronous',
    'FCPO_AMAZONPAY_MODE_FIRSTSYNCTHENSYNC'     => 'Synchronous, asynchronous as fallback',
    'FCPO_AMAZONPAY_LOGINMODE'                  => 'Login method',
    'FCPO_AMAZONPAY_LOGINMODE_AUTO'             => 'Automatically (SSL "Popup" and no "Redirect")',
    'FCPO_AMAZONPAY_LOGINMODE_POPUP'            => 'Popup (requires SSL)',
    'FCPO_AMAZONPAY_LOGINMODE_REDIRECT'         => 'Redirect',

    'FCPO_PROFILES_RATEPAY'               => 'Ratepay Profile',
    'FCPO_RATEPAY_DELETE_PROFILE'         => 'Delete profile',
    'FCPO_RATEPAY_ADD_PROFILE'            => 'Add profile',
    'FCPO_PROFILES_RATEPAY_CURRENCY'      => 'Currency',
    'FCPO_PROFILES_RATEPAY_PAYMENT'       => 'Ratepay Payment method',
    'FCPO_RATEPAY_PROFILE_TOGGLE_DETAILS' => 'Toggle configuration details',
    'FCPO_RATEPAY_PROFILE_DETAILS_FOR_ID' => 'Profile configuration for ShopID',
    'FCPO_RATEPAY_GENERAL_SETTINGS'       => 'Ratepay Settings',
    'FCPO_RATEPAY_B2BMODE'                => 'Enable Ratepay B2B-Mode',
    'FCPO_HELP_RATEPAY_B2BMODE'           => 'If B2B-Mode is enabled Vat-Id and company name will be requested, birthday for B2C customers',

    'FCPO_PAYOLUTION_B2BMODE'          => 'Activate Payolution B2B-Mode',
    'FCPO_HELP_PAYOLUTION_B2BMODE'     => 'If B2B-Mode is enabled Vat-Id and company name will be requested, birthday for B2C customers',
    'FCPO_PAYOLUTION_COMPANY'          => 'Company name',
    'FCPO_HELP_PAYOLUTION_COMPANY'     => 'Will be displayed at agreement statement',
    'FCPO_PAYOLUTION_MODE'             => 'Enable Payolution test mode',
    'FCPO_PAYOLUTION_AUTH_USER'        => 'Payolution User name',
    'FCPO_HELP_PAYOLUTION_AUTH_USER'   => 'User name for Authentification',
    'FCPO_PAYOLUTION_AUTH_SECRET'      => 'Payolution Password',
    'FCPO_HELP_PAYOLUTION_AUTH_SECRET' => 'Password for Authentification',

    'fcpo_admin_config_payone_error_message'     => 'PAYONE error message',
    'fcpo_admin_config_status_language'          => 'Language',
    'fcpo_admin_config_status_own_error_message' => 'Custom error message',

    'FCPO_CONFIG_DEBIT_BANKDATA'        => "Input bank account data",
    'FCPO_CONFIG_DEBIT_MULTISELECT'     => "Country control list (hold CTRL for multiselect)",
    'FCPO_CONFIG_DEBIT_GER'             => "German bank accounts only",
    'FCPO_CONFIG_DEBIT_SHOW_OLD_FIELDS' => "display bank account number and code in addition",

    'FCPO_CONFIG_DEBIT_MANDATE'                 => "Mandate process",
    'FCPO_CONFIG_DEBIT_MANDATE_TEXT'            => 'Requires chargeable "managemandate" request including bank account check. No POS blacklist check possible',
    'FCPO_CONFIG_DEBIT_MANDATE_ACTIVE'          => "Activate mandate process",
    'FCPO_CONFIG_DEBIT_MANDATE_DOWNLOAD'        => "Download Mandat as PDF",
    'FCPO_CONFIG_DEBIT_MANDATE_DOWNLOAD_TEXT'   => 'Only available if PAYONE procuct<br>"SEPA-Mandate as PDF" is active.',
    'FCPO_CONFIG_DEBIT_MANDATE_DOWNLOAD_ACTIVE' => "Download Mandat as PDF",

    'fcpo_admin_config_error_iframe_mapping' => 'Custom error message for hosted iFrame',
    'fcpo_admin_config_payone_error_code'    => 'Error code',

    'FCPO_SHOW_IBAN_FIELDS' => 'Display IBAN/BIC',


    'FCPO_PREAUTHORIZED_AMOUNT'        => 'Preauthorized amount',
    'FCPO_AUTHORIZED_AMOUNT'           => 'Authorized amount',
    'FCPO_PAID_AMOUNT'                 => 'Paid on ',
    'FCPO_LEFT_PREAUTHORIZED_AMOUNT'         => 'Remain to capture ',
    'FCPO_CAPTURED_AMOUNT'             => 'Captured amount',
    'FCPO_CAPTURED_AMOUNT_TOTAL'       => 'Total',
    'FCPO_REFUNDED_AMOUNT'             => 'Refunded amount',
    'FCPO_REFUNDED_AMOUNT_TOTAL'       => 'Total',
    'FCPO_CAPTURE_AMOUNT_GREATER_NULL' => 'Captured amount has to be greater than 0',

    'FCPO_HELP_ASSIGNCOUNTRIES_2' => 'If no country is assigned, this payment method will be available for all countries',



    'FCPO_CONFIG_GROUP_PP_EXPRESS_LOGOS' => "PayPal",
    'FCPO_CONFIG_ADD_PP_EXPRESS_LOGO'    => "Add another language",

    'FCPO_HELP_REFPREFIX' => "A unique referencenumber has to be transferred to PAYONE with every request. This is a consecutive number, normally starting at 1. When operating multiple shops ( e.g. live- and test-shop ) with the same PAYONE account-data there will be problems when the current referencenumber was already used. This can be avoided by using different prefixes on different shops.",
    'FCPO_REFPREFIX'      => "Referencenumber prefix ( optional )",

    'FCPO_MANDATE_PDF'      => "SEPA mandate-pdf",
    'FCPO_MANDATE_DOWNLOAD' => "download",

    'FCPO_EXPORT_CONFIG' => "Export configuration",

    'FCPO_PAYPAL_DELADDRESS'         => 'Transmit the billing-address as delivery-address if delivery-address is missing.',
    'FCPO_HELP_PAYPAL_DELADDRESS'    => 'This is used for the PayPal seller protection.',
    'FCPO_PAYPAL_LOGOS'              => 'You can upload the PayPal Express logos here.',
    'FCPO_PAYPAL_LOGOS_ACTIVE'       => 'active',
    'FCPO_PAYPAL_LOGOS_LANG'         => 'language',
    'FCPO_PAYPAL_LOGOS_LOGO'         => 'logo',
    'FCPO_PAYPAL_LOGOS_UPLOAD'       => 'upload',
    'FCPO_PAYPAL_LOGOS_DEFAULT'      => 'default',
    'FCPO_PAYPAL_LOGOS_NOT_EXISTING' => 'No logo existing!',

    'ORDER_OVERVIEW_FCPO_ELV_BLZ'   => "Bank Code",
    'ORDER_OVERVIEW_FCPO_ELV_KTONR' => "Account No.",
    'ORDER_OVERVIEW_FCPO_ELV_IBAN'  => "IBAN",
    'ORDER_OVERVIEW_FCPO_ELV_BIC'   => "BIC",

    'FCPO_CC_CONFIG'         => 'Input-configuration',
    'FCPO_CC_STANDARD_STYLE' => 'Standard-style',
    'FCPO_CC_ERRORS'         => 'Error-output',

    'FCPO_CC_STANDARD_INPUT'     => 'Input',
    'FCPO_CC_STANDARD_SELECTION' => 'Selection',
    'FCPO_CC_STANDARD_FIELDS'    => 'Input-fields',
    'FCPO_CC_STANDARD_IFRAME'    => 'Iframe',

    'FCPO_CC_ACTIVE'   => 'Active',
    'FCPO_CC_LANGUAGE' => 'Language',
    'FCPO_CC_SELECT'   => 'Selection',

    'FCPO_CC_ERRORLANG_DE'    => 'German',
    'FCPO_CC_ERRORLANG_EN'    => 'English',
    'FCPO_CC_CUSTOM_TEMPLATE' => 'Custom styling hosted-Iframe',
    'FCPO_CC_PREVIEW'         => 'Preview',

    'FCPO_CREDITCARD'         => 'Credit card:',
    'FCPO_NUMBER'             => 'Number:',
    'FCPO_CARD_SECURITY_CODE' => 'CVV2 or CVC2 security code:',
    'FCPO_VALID_UNTIL'        => 'Valid until:',
    'FCPO_FIRSTNAME'          => 'Firstname:',
    'FCPO_LASTNAME'           => 'Lastname:',

    'FCPO_PREVIEW_NOTICE' => 'You need to save before the changes are visible in the preview!',

    'FCPO_CC_TYPE'      => "Request-type",
    'FCPO_HELP_CC_TYPE' => "hosted-Iframe: The input-fields are delivered in Iframes which are hosted by PAYONE ( PCI DSS 3.0 conform ).<br>AJAX - The creditcard-information is sent to PAYONE via AJAX",

    'FCPO_CC_HEADER_TYPE'        => 'Type',
    'FCPO_CC_HEADER_DIGIT_COUNT' => 'Digit-<br>count',
    'FCPO_CC_HEADER_DIGIT_MAX'   => 'Max-<br>digits',
    'FCPO_CC_HEADER_IFRAME'      => 'Iframe',
    'FCPO_CC_HEADER_WIDTH'       => 'Width',
    'FCPO_CC_HEADER_HEIGHT'      => 'Height',
    'FCPO_CC_HEADER_STYLE'       => 'Style',
    'FCPO_CC_HEADER_CSS'         => 'CSS',

    'FCPO_CC_ROW_CC_Number' => 'Creditcardnumber',
    'FCPO_CC_ROW_CC_CVC'    => 'CVC security code',
    'FCPO_CC_ROW_CC_Month'  => 'Validity-month',
    'FCPO_CC_ROW_CC_Year'   => 'Validity-year',

    'FCPO_CC_TYPE_NUMERIC'  => 'Numeric',
    'FCPO_CC_TYPE_PASSWORD' => 'Password',
    'FCPO_CC_TYPE_TEXT'     => 'Text',

    'FCPO_CC_IFRAME_STANDARD'                          => 'Standard',
    'FCPO_CC_IFRAME_CUSTOM'                            => 'Custom',
    'FCPO_CC_USE_CVC'                                  => 'Use CVC as mandatory field',
    'FCPO_CONFIG_DEBIT_BIC_MANDATORY'                  => 'Entering BIC is mandatory',
    'FCPO_CONFIG_GROUP_SECINVOICE'                     => 'Secure Invoice (rec/POV)',
    'FCPO_CONFIG_GROUP_BNPL'                           => 'BNPL Zahlarten (fnc/PIV, fnc/PIN)',
    'FCPO_SECINVOICE_PORTAL_ID'                        => 'PAYONE Portal ID (for payment Secure Invoice)',
    'FCPO_BNPL_PORTAL_ID'                              => 'PAYONE Portal ID (for payment BNPL)',
    'FCPO_SECINVOICE_PORTAL_KEY'                       => 'PAYONE Portal Key (for payment Secure Invoice)',
    'FCPO_BNPL_PORTAL_KEY'                             => 'PAYONE Portal Key (for payment BNPL)',
    'FCPO_BNPL_ALLOW_DIFF_ADDRESS'                     => 'Allow different shipping address',
    'FCPO_BNPL_ADMIN_DEBIT_REASON_TITLE'               => 'Cancellation reason',
    'FCPO_BNPL_CANCELLATION_REASON_CRQ'                => 'The consumer requested a cancellation of the Order',
    'FCPO_BNPL_CANCELLATION_REASON_DUP'                => 'The Order was created twice accidentally',
    'FCPO_BNPL_CANCELLATION_REASON_FRD'                => 'Consumer turned out to be a fraudster',
    'FCPO_BNPL_CANCELLATION_REASON_UND'                => 'The merchant cannot fulfill the Order',
    'FCPO_GROUP_LOGGING'                               => 'Logging',
    'FCPO_TRANSACTIONREDIRECTLOGGING_NONE'             => 'No logs (Default)',
    'FCPO_TRANSACTIONREDIRECTLOGGING_ALL'              => 'Log everything',
    'FCPO_TRANSACTIONREDIRECTLOGGING'                  => 'Logging of transactionstatus redirects',
    'FCPO_HELP_TRANSACTIONREDIRECTLOGGING'             => 'With this option activated, you can log activity of transactionstatus redirects. Content of this logging are landing in file <i>fcpo_message_forwarding.log</i> in your shops log folder. Please note, that this option should not be activated all the time due to it produces big log files',
    'FCPO_HASH_METHOD'                                 => 'Hash Method',
    'FCPO_HELP_HASH_METHOD'                            => 'Here you can setup the hash method which will be used for communication with Payone-API. If possible, use sha2-384',
    'FCPO_EMAIL_CLEARING_SUBJECT'                      => 'Ihre Überweisungsdaten zur Bestellnummer',
    'FCPO_EMAIL_CLEARING_BODY_WELCOME'                 => "Hallo %NAME% %SURNAME%,\nzur Begleichung der Rechnung verwenden Sie bitte folgende Daten zur Überweisung:\n\n",
    'FCPO_EMAIL_BANK'                                  => 'Bank:',
    'FCPO_EMAIL_ROUTINGNUMBER'                         => 'Bank Code:',
    'FCPO_EMAIL_ACCOUNTNUMBER'                         => 'Account No.:',
    'FCPO_EMAIL_BIC'                                   => 'BIC:',
    'FCPO_EMAIL_IBAN'                                  => 'IBAN:',
    'FCPO_EMAIL_CLEARING_BODY_THANKYOU'                => 'Thank you, your %SHOPNAME%-Team',
    'FCPO_EMAIL_USAGE'                                 => 'Usage',
    'FCPO_TRANSACTIONREDIRECTMETHOD_DIRECT'            => 'Direct redirect (Standard)',
    'FCPO_TRANSACTIONREDIRECTMETHOD_CRONJOB'           => 'Delayed by Cronjob (Secure transaction)',
    'FCPO_HELP_TRANSACTIONREDIRECTMETHOD'              => 'Choose the method how transaction redirects will be handled. There are two choices:<br><b>Direct redirect:</b><br>Using this method will directly redirect the transaction after receiving it. This mode offers a high redirection speed and a moderate transaction security.<br><b>Delayed by Cronjob:</b><br>Instead of directly redirecting the statusmessage, this method collects incoming messages and will redirect them aftery calling a cronjob. This mode offers a very high transaction security. The speed of redirecting statusmessages depends on the setup of your server. Please visit the <a href="">manual</a> for further information for setting this up efficiantly.',
    'FCPO_TRANSACTIONREDIRECTMETHOD'                   => 'Method of statusmessage redirecting',
    'FCPO_TRANSACTION_TIMEOUT'                         => 'Timeout in seconds',
    'FCPO_HELP_TRANSACTIONREDIRECT_TIMEOUT'            => 'For offering direct redirects without any interruptions, there is a need for having a timout. Depending on the setup of your server it can be nessessary to have a higher value then 10s default.',
    'FCPO_FORWARD_REDIRECTS'                           => 'Transaction status redirects',
    'FCPO_FORWARD_REDIRECT_TARGETURL'                  => 'Target',
    'FCPO_FORWARD_REDIRECT_TRIES'                      => 'Tries',
    'FCPO_FORWARD_REDIRECT_LASTTRY'                    => 'Last tried',
    'FCPO_FORWARD_REDIRECT_FULFILLED'                  => 'Success',
    'FCPO_FORWARD_REDIRECT_FULFILLED_YES'              => 'Yes',
    'FCPO_FORWARD_REDIRECT_FULFILLED_NO'               => 'No',
    'FCPO_FORWARD_REDIRECT_DETAILS'                    => 'Details',
    'FCPO_FORWARD_REDIRECT_TRIGGER'                    => 'Trigger all missing/unfulfilled calls',

    'FCPO_CONFIG_GROUP_APPLE_PAY'                      => "Apple Pay",
    'FCPO_HELP_APPLE_PAY_MERCHANT_ID'                  => "Merchant ID",
    'FCPO_APPLE_PAY_MERCHANT_ID'                       => "Merchant ID",
    'FCPO_HELP_APPLE_PAY_CERTIFICATE'                  => "The name of the certificate is taken from the text field. It can be changed to any wished name. If empty when saving uploaded file, it will by default take the file\'s initial name.<br/>The text field can also be used to name an existing certificate file on the server, without uploading a new file.",
    'FCPO_APPLE_PAY_CERTIFICATE'                       => "Merchant Identification Certificate file",
    'FCPO_APPLE_PAY_CONFIG_CERTIFICATE_MISSING'        => "The current configured certificate file doesn't exist.<br/>Apple Pay cannot be used as payment method.",
    'FCPO_HELP_APPLE_PAY_KEY'                          => "This is a multiple field. You can upload a file containing the key, or type the content of the key directly into the text area below. Priority goes to uploaded file if both options are used !<br/><br/>
The smaller text field is used to name the destination file, or path to an existing key file on server.<br/>
- If empty while saving uploaded file, it will take the uploaded file's initial name.<br/>
- If empty while saving direct input, it will take the default name 'merchant_id.key'.<br/>
- If empty while not doing any of those, it will take an empty value.",
    'FCPO_APPLE_PAY_KEY'                               => "Certificate private key",
    'FCPO_HELP_APPLE_PAY_PASSWORD'                     => "Certificate key password",
    'FCPO_APPLE_PAY_PASSWORD'                          => "Certificate key password",
    'FCPO_APPLE_PAY_CREDITCARD'                        => "Allowed credit cards to use with Apple Pay",
    'FCPO_APPLE_PAY_CREATE_SESSION_ERROR'              => "Error while establishing connection to Apple Pay service.",
    'FCPO_APPLE_PAY_CREATE_SESSION_ERROR_CARDS'        => "No valid credit cards type is allowed in the configuration. Apple Pay session cannot be initialized.",

    'FCPO_SHADOW_BASKET'                               => 'Shadow-Basket',
    'FCPO_POSSIBLE_FRAUD_DETECTED'                     => 'A possible fraud has been detected. Please compare this previously saved basket with order.',
    'FCPO_GENERAL_SHADOWBASKET_BRUTTO'                 => 'Brutsum of Shadowbasket',
    'FCPO_GENERAL_SHADOWBASKET_NETTO'                  => 'Netsum of Shadowbasket',

    'PAYONE Alipay' => 'PAYONE Alipay',
    'PAYONE Amazon Pay' => 'PAYONE Amazon Pay',
    'PAYONE Apple Pay' => 'PAYONE Apple Pay',
    'PAYONE Bancontact' => 'PAYONE Bancontact',
    'PAYONE Barzahlen' => 'PAYONE Barzahlen',
    'PAYONE eps Überweisung' => 'PAYONE eps',
    'PAYONE Gesicherter Rechnungskauf' => 'PAYONE Secure Invoice',
    'PAYONE Gesicherter Rechnungskauf (neu)' => 'PAYONE Secured Invoice (new)',
    'PAYONE Gesicherter Ratenkauf' => 'PAYONE Secured Installment',
    'PAYONE Gesicherte Lastschrift' => 'PAYONE Secured Direct Debit',
    'PAYONE Giropay' => 'PAYONE Giropay',
    'PAYONE iDEAL' => 'PAYONE iDEAL',
    'PAYONE Klarna Ratenkauf' => 'PAYONE Klarna Ratenkauf',
    'PAYONE Klarna Rechnung' => 'PAYONE Klarna Rechnung',
    'PAYONE Klarna Sofort bezahlen' => 'PAYONE Klarna Sofort bezahlen',
    'PAYONE Kreditkarte' => 'PAYONE Credit Card',
    'PAYONE Lastschrift' => 'PAYONE Direct Debit',
    'PAYONE Nachnahme' => 'PAYONE Cash on Delivery',
    'PAYONE paydirekt' => 'PAYONE paydirekt',
    'PAYONE PayPal Express' => 'PAYONE PayPal Express',
    'PAYONE PayPal' => 'PAYONE PayPal',
    'PAYONE PostFinance Card' => 'PAYONE PostFinance Card',
    'PAYONE PostFinance E-Finance' => 'PAYONE PostFinance E-Finance',
    'PAYONE Przelewy24' => 'PAYONE Przelewy24',
    'PAYONE Ratepay Rechnungskauf' => 'PAYONE Ratepay Open Invoice',
    'PAYONE Ratepay Lastschrift' => 'PAYONE Ratepay Direct Debit',
    'PAYONE Ratepay Ratenkauf' => 'PAYONE Ratepay Installments',
    'PAYONE Rechnungskauf' => 'PAYONE Invoice',
    'PAYONE Sofort Überweisung' => 'PAYONE Sofort',
    'PAYONE Trustly' => 'PAYONE Trustly',
    'PAYONE Unzer Lastschrift' => 'PAYONE Unzer Lastschrift',
    'PAYONE Unzer Ratenkauf' => 'PAYONE Unzer Ratenkauf',
    'PAYONE Unzer Rechnungskauf' => 'PAYONE Unzer Rechnungskauf',
    'PAYONE Vorkasse' => 'PAYONE prepayment',
    'PAYONE WeChat Pay' => 'PAYONE WeChat Pay',
    'FCPO_KLARNA' => 'PAYONE Klarna Payments',
);

/*
[{ oxmultilang ident="GENERAL_YOUWANTTODELETE" }]
*/
