<?php
/**
 * PAYONE OXID Connector is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PAYONE OXID Connector is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with PAYONE OXID Connector.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @link      http://www.payone.de
 * @copyright (C) Payone GmbH
 * @version   OXID eShop CE
 */


$sLangName = "Deutsch";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset'                                   => 'UTF-8',
    'fcpo_admin_title'                          => 'PAYONE',
    'fcpo_main_title'                           => 'Konfiguration',
    'fcpo_main_log'                             => 'Transaktionen',
    'FCPO_MERCHANT_ID'                          => 'PAYONE Merchant ID',
    'FCPO_PORTAL_ID'                            => 'PAYONE Portal ID',
    'FCPO_PORTAL_KEY'                           => 'PAYONE Portal Key',
    'FCPO_OPERATION_MODE'                       => 'PAYONE Betriebsmodus',
    'FCPO_SUBACCOUNT_ID'                        => 'PAYONE Sub-Account ID',
    'FCPO_LIVE_MODE'                            => 'Livemodus',
    'FCPO_TEST_MODE'                            => 'Testmodus',
    'fcpo_order_title'                          => 'PAYONE',
    'FCPO_REFNR'                                => 'Referenz-Nummer',
    'FCPO_TXID'                                 => 'PAYONE-Vorgangsnummer (txid)',
    'fcpo_action_appointed'                     => 'Bestellung',
    'fcpo_action_capture'                       => 'Abbuchung',
    'fcpo_action_paid'                          => 'Bezahlung',
    'fcpo_action_underpaid'                     => 'Unterzahlung',
    'fcpo_action_overpaid'                      => '<span style="color: red;">überzahlung</span>',
    'fcpo_action_cancelation'                   => 'Rückbelastung',
    'fcpo_action_refund'                        => 'Rückerstattung',
    'fcpo_action_debit'                         => 'Forderung/Gutschrift',
    'fcpo_action_transfer'                      => 'Umbuchung',
    'fcpo_action_reminder'                      => 'Status Mahnverfahren',
    'fcpo_clearingtype_elv'                     => 'Lastschrift',
    'fcpo_clearingtype_cc'                      => 'Kreditkarte',
    'fcpo_clearingtype_vor'                     => 'Vorkasse',
    'fcpo_clearingtype_rec'                     => 'Rechnung',
    'fcpo_clearingtype_cod'                     => 'Nachnahme',
    'fcpo_clearingtype_sb'                      => 'Online-Überweisung',
    'fcpo_clearingtype_wlt'                     => 'e-Wallet',
    'fcpo_clearingtype_fnc'                     => 'Finanzierung',
    'fcpo_clearingtype_csh'                     => 'Barzahlen',
    'fcpo_clearingtype_fcpoklarna'              => 'Klarna Rechnung',
    'fcpo_clearingtype_fcpoklarna_invoice'      => 'Klarna pay later',
    'fcpo_clearingtype_fcpoklarna_installments' => 'Klarna slice it',
    'fcpo_clearingtype_fcpoklarna_directdebit'  => 'Klarna pay now',
    'fcpo_clearingtype_fcpopo_bill'             => 'Unzer Rechnungskauf',
    'fcpo_clearingtype_fcpopo_debitnote'        => 'Unzer Lastschrift',
    'fcpo_clearingtype_fcpopo_installment'      => 'Unzer Ratenkauf',
    'fcpo_clearingtype_fcporp_debitnote'        => 'Ratepay Lastschrift',
    'fcpo_clearingtype_fcporp_bill'             => 'Ratepay Rechnungskauf',
    'fcpo_clearingtype_fcporp_installment'      => 'Ratepay Ratenkauf',
    'fcpo_clearingtype_fcpopl_secinvoice'       => 'BNPL Gesicherter Rechnungskauf',
    'fcpo_clearingtype_fcpopl_secinstallment'   => 'BNPL Gesicherter Ratenkauf',
    'fcpo_clearingtype_fcpopl_secdebitnote'     => 'BNPL Gesicherte Lastschrift',
    'FCPO_CAPTURE_APPROVED'                     => 'Buchung war erfolgreich',
    'FCPO_CAPTURE_ERROR'                        => 'Fehler bei Buchung: ',
    'FCPO_DEBIT_APPROVED'                       => 'Gutschrift war erfolgreich',
    'FCPO_DEBIT_ERROR'                          => 'Fehler bei Gutschrift: ',
    'FCPO_AMOUNT_IN'                            => 'Betrag in',
    'FCPO_LIST_HEADER_TITLE'                    => 'Transaktionskonto',
    'FCPO_LIST_HEADER_TXTIME'                   => 'Zeitpunkt',
    'FCPO_LIST_HEADER_PROCESS'                  => 'Vorgang',
    'FCPO_LIST_HEADER_DEMAND'                   => 'Forderung',
    'FCPO_LIST_HEADER_ORDERNR'                  => 'Bestellnummer',
    'FCPO_LIST_HEADER_TXID'                     => 'Transaktionsnummer',
    'FCPO_LIST_HEADER_CLEARINGTYPE'             => 'Zahlmethode',
    'FCPO_LIST_HEADER_EMAIL'                    => 'Kunden-E-Mail',
    'FCPO_LIST_HEADER_PRICE'                    => 'Betrag',
    'FCPO_LIST_HEADER_TXACTION'                 => 'Status',
    'FCPO_LIST_HEADER_FORWARD_STATE'            => 'Forward Status',
    'FCPO_LIST_HEADER_FORWARD_TRIES'            => 'Forward Versuche',
    'FCPO_EXECUTE'                              => 'Auslösen',
    'FCPO_CAPTURE'                              => 'Capture ( Abbuchen )',
    'FCPO_DEBIT'                                => 'Debit ( Gutschrift )',
    'FCPO_ARE_YOU_SURE'                         => 'Sind Sie sicher, dass Sie diese Aktion ausführen möchten?',
    'FCPO_DE'                                   => 'Deutschland',
    'FCPO_AT'                                   => 'Österreich',
    'FCPO_NL'                                   => 'Niederlande',
    'FCPO_HEADER_BANKACCOUNT'                   => 'Bankverbindung (optional)',
    'FCPO_BANKCOUNTRY'                          => 'Kontoland',
    'FCPO_BANKACCOUNT'                          => 'Kontonummer',
    'FCPO_BANKCODE'                             => 'Bankleitzahl',
    'FCPO_BANKACCOUNTHOLDER'                    => 'Kontoinhaber',
    'FCPO_SHOW'                                 => 'anzeigen',
    'FCPO_HIDE'                                 => 'verstecken',
    'FCPO_PAYMENTTYPE'                          => 'Zahlungsart',
    'FCPO_CARDEXPIREDATE'                       => 'Verfallsdatum',
    'FCPO_CARDTYPE'                             => 'Kartentyp',
    'FCPO_CARDPAN'                              => 'Maskierte Kartenummer',
    'FCPO_BALANCE'                              => 'Saldo',
    'FCPO_RECEIVABLE'                           => 'Zahlung',
    'FCPO_NO_TRANSACTION_STATUS_RECEIVED'       => 'Kein Transaktions-Status eingegangen.',
    'FC_IS_PAYONE'                              => 'Dies ist eine PAYONE Zahlungsmethode',
    'FCPO_HELP_MERCHANTID'                      => 'Ihre PAYONE Merchant-ID (PAYONE Kundennummer) finden Sie auf allen Abrechnungen von PAYONE sowie rechts oben im PAYONE Merchant Interface (PMI).',
    'FCPO_HELP_PORTALID'                        => 'Bitte tragen Sie hier die ID des PAYONE Zahlungsportals ein, über welches die Zahlungen abgewickelt werden sollen.<br>Die Portal-ID finden Sie unter <a href="http://www.payone.de" target="_blank">http://www.payone.de</a> > Händler-Login unter dem Menüpunkt Konfiguration > Zahlungsportale<br><br>Alle relevanten Parameter zur Konfiguration erhalten Sie nach Auswahl von [editieren] unter dem Reiter [API-Parameter]',
    'FCPO_HELP_PORTALKEY'                       => 'Bitte tragen Sie hier den Key zur Absicherung des Datenaustausches ein. Dieser kann bei der Konfiguration des PAYONE Zahlungsportals von Ihnen frei festgelegt werden.<br>Die Konfiguration finden Sie unter <a href="http://www.payone.de" target="_blank">http://www.payone.de</a> > Handler-Login unter dem Menüpunkt Konfiguration > Zahlungsportale > [editieren] > Reiter [Erweitert] > Key<br><br>Alle relevanten Parameter zur Konfiguration erhalten Sie nach Auswahl des Reiters [API-Parameter]',
    'FCPO_HELP_OPERATIONMODE'                   => 'Hier können Sie für diese Zahlungsart festlegen ob die Zahlungen im Testmodus abgewickelt werden, oder ob diese Live ausgeführt werden. Bitte beachten Sie, dass für den Testmodus die definierten Testdaten verwendet werden müssen.',
    'FCPO_HELP_SUBACCOUNTID'                    => 'Bitte tragen Sie hier die ID des Sub-Accounts ein, über welchen die Zahlungen abgewickelt und zugeordnet werden sollen.<br>Die ID finden Sie unter <a href="http://www.payone.de" target="_blank">http://www.payone.de</a> > Händler-Login unter dem Menüpunkt Konfiguration > Accounts<br><br>Alle relevanten Parameter zur Konfiguration erhalten Sie unter <a href="http://www.payone.de" target="_blank">http://www.payone.de</a> > Händler-Login unter dem Menüpunkt Konfiguration > Zahlungsportale > [editieren] > Reiter [API-Parameter]',
    'fcpo_admin_config'                         => 'PAYONE Konfiguration',
    'fcpo_admin_config_payment'                 => 'PAYONE Zahlungseinstellungen',
    'fcpo_admin_protocol'                       => 'PAYONE Protokolle / Logs',
    'FCPO_NO_TRANSACTION'                       => 'Keine Transaktion ausgewählt',
    'fcpo_admin_information'                    => 'PAYONE Information',
    'fcpo_admin_common'                         => 'Allgemein',
    'fcpo_admin_support'                        => 'Support',
    'fcpo_admin_api_logs'                       => 'API Logs',
    'FCPO_LIST_HEADER_TIMESTAMP'                => 'Zeit',
    'FCPO_LIST_HEADER_REQUEST'                  => 'Request',
    'FCPO_LIST_HEADER_RESPONSE'                 => 'Response',
    'FCPO_NO_APILOG'                            => 'Kein Log-Eintrag ausgewählt',
    'FCPO_ACTIVE_CREDITCARD_TYPES'              => 'Aktive Kreditkartenbrands',
    'FCPO_CREDITCARDBRANDS_INFOTEXT'            => 'Hier können Sie die einzelnen Kreditkartenbrands für die Zahlart Kreditkarte aktivieren und konfigurieren.<br>Bitte beachten Sie, dass der jeweilige Kreditkartenbrand bei PAYONE beauftragt worden sein muss.<br>Die Einstellung für die Zahlungsart Kreditkarte nehmen Sie unter PAYONE -> Konfiguration -> Zahlungsarten vor.',
    'FCPO_ACTIVE_ONLINE_UBERWEISUNG_TYPES'      => 'Aktive Online-überweisungsarten',
    'FCPO_ONLINEUBERWEISUNG_INFOTEXT'           => 'Hier können Sie die einzelnen Online-überweisungsarten für die Zahlart Online-überweisung aktivieren und konfigurieren.<br>Bitte beachten Sie, dass die jeweilige Online-überweisungsart bei PAYONE beauftragt worden sein muss.<br>Die Einstellung für die Zahlungsart Online-überweisungsart nehmen Sie unter PAYONE -> Konfiguration -> Zahlungsarten vor.',
    'FCPO_CHANNEL'                              => 'Channel',
    'FCPO_AUTHORIZATION_METHOD'                 => 'Autorisierungs-Methode',
    'FCPO_PREAUTHORIZATION'                     => 'Vorautorisierung',
    'FCPO_PREAUTHORIZATION_HELP'                => 'Bei der Auswahl von "Vorautorisierung" wird der zu zahlende Betrag im Zuge der Bestellung reserviert [von PAYONE empfohlen]. Die Abbuchung (Capture) muss in diesem Fall in einem zweiten Schritt bei Auslieferung der Ware initiiert werden.',
    'FCPO_AUTHORIZATION'                        => 'Autorisierung',
    'FCPO_AUTHORIZATION_HELP'                   => 'Bei der Auswahl von "Autorisierung" wird der zu zahlende Betrag sofort im Zuge der Bestellung eingezogen.',
    'dyn_fcpayone'                              => 'PAYONE',
    'FCPO_ONLY_PAYONE'                          => 'Nur PAYONE',
    'ORDER_LIST_YOUWANTTOSTORNO'                => 'Wollen Sie diese Bestellung wirklich stornieren?\n ACHTUNG: ggf. offene PAYONE Vorgänge zu dieser Bestellung bitte vor dem Stornieren abschliessen.',
    'FCPO_ORDER_LIST_YOUWANTTODELETE'           => 'Wollen Sie diesen Eintrag wirklich löschen?\n ACHTUNG: ggf. offene PAYONE Vorgänge zu dieser Bestellung bitte vor dem Löschen abschliessen.',
    'FCPO_SEND_ARTICLELIST'                     => 'Artikelliste versenden',
    'FCPO_HELP_SEND_ARTICLELIST'                => 'Bei Aktivierung wird in den vorgesehenen Anfragen an das PAYONE System der Warenkorb incl. der Artikeleinzelpreise mit versendet.<br>Diese Option muss aktiviert sein wenn sie das PAYONE Invoicing beauftragt haben.',
    'FCPO_STATUS_WITH_USER_CORRECTION'          => 'User wird wieder zum Benutzerformular geschickt wenn:',
    'FCPO_MODULE_VERSION'                       => 'Version Modul',
    'FCPO_HELP_ASSIGNCOUNTRIES'                 => 'Wenn keine Länder zugewiesen sind, gilt die Zahlungsart für alle Länder.<br><br>Wenn Länder zugewiesen sind gelten die Zahlungsarten nur für die zugewiesenen Länder.<br><br>geprüft werden Rechnungsland und Lieferland.',
    'FCPO_HELP_ASSIGNCOUNTRIES_2'               => 'Wenn keine Länder zugewiesen sind, gilt die Zahlungsart für alle Länder.<br><br>Wenn Länder zugewiesen sind gelten die Zahlungsarten nur für die zugewiesenen Länder.<br><br>geprüft werden Rechnungsland und Lieferland.',
    'fcpo_receivable_appointed1'                => 'Reservierung',
    'fcpo_receivable_appointed2'                => 'Forderung (Autorisierung)',
    'fcpo_receivable_capture'                   => 'Forderung (Capture)',
    'fcpo_receivable_debit1'                    => 'Forderung (Debit)',
    'fcpo_receivable_debit2'                    => 'Gutschrift (Debit/Refund)',
    'fcpo_receivable_reminder'                  => 'Mahnungsversand',
    'fcpo_receivable_cancelation'               => 'Rücklastschriftgebühr',
    'fcpo_payment_capture1'                     => 'Einzug',
    'fcpo_payment_capture2'                     => 'Auszahlung',
    'fcpo_payment_paid1'                        => 'Zahlungseingang',
    'fcpo_payment_paid2'                        => 'Rückbelastung',
    'fcpo_payment_underpaid1'                   => 'Unterzahlung',
    'fcpo_payment_underpaid2'                   => 'Rückbelastung',
    'fcpo_payment_debit1'                       => 'Einzug',
    'fcpo_payment_debit2'                       => 'Auszahlung',
    'fcpo_payment_transfer'                     => 'Umbuchung',
    'fcpo_payment'                              => 'Zahlung',
    'FCPO_MAIN_CONFIG_INFOTEXT'                 => 'Sie können für jede Zahlart einzeln konfigurieren, ob diese im Test- oder Livemodus abgewickelt werden soll. Die Einstellung finden Sie unter PAYONE -> Konfiguration -> Zahlungsarten. Wir empfehlen Ihnen nach der initialen Konfiguration sowie bei Konfigurationsänderungen zunächst alle Zahlungsprozesse im Testmodus durchzuführen.',
    'FCPO_MAIN_CONFIG_TESTACCOUNT_LINK'         => 'Sie brauchen einen Testkonto? Eröffnen Sie ein unverbindliches Testkonto <a href="https://www.payone.com/DE-de/kampagne/ecom-testaccount" target="_blank">>>hier<<</a>',
    'FCPO_INFOTEXT_SET_OPERATIONMODE'           => 'Wird individuell eingestellt unter PAYONE->Konfiguration->Zahlungseinstellungen',
    'FCPO_SETTLE_ACCOUNT'                       => 'Saldenausgleich durchführen',
    'FCPO_HELP_SETTLE_ACCOUNT'                  => 'Deaktivieren sie für Teileinzüge die Checkbox "Saldenausgleich durchführen". Bei der letzten Teillieferung muss diese Option aktiviert werden, um einen Kontenausgleich durchzuführen.',
    'FCPO_CAPTURE_AMOUNT_GREATER_NULL'          => 'Der Betrag für einen Capture muss größer als 0,00 sein!',
    'FCPO_PREAUTHORIZED_AMOUNT'                 => 'Vorautorisierter Betrag',
    'FCPO_AUTHORIZED_AMOUNT'                    => 'Autorisierter Betrag',
    'FCPO_PAID_AMOUNT'                          => 'Bezahlt am ',
    'FCPO_LEFT_PREAUTHORIZED_AMOUNT'            => 'Bleibt noch zu einziehen ',
    'FCPO_CAPTURED_AMOUNT'                      => 'Eingezogenen Betrag',
    'FCPO_CAPTURED_AMOUNT_TOTAL'                => 'Total',
    'FCPO_REFUNDED_AMOUNT'                      => 'Gutgeschriebenen Betrag',
    'FCPO_REFUNDED_AMOUNT_TOTAL'                => 'Total',
    'FCPO_PRESAVE_ORDER'                        => 'Bestellung vor Authorisierung speichern',
    'FCPO_REDUCE_STOCK'                         => 'Lagerbestand reduzieren',
    'FCPO_HELP_REDUCE_STOCK'                    => 'Diese Einstellung hat nur Effekt wenn "Bestellung vor Authorisierung speichern" aktiviert ist und man während dem Bestellvorgang zur Bezahlung zu einem externen Bezahldienst ( z.B. Sofortüberweisung, PayPal oder Kreditkarte mit 3D Secure ) weitergeleitet wird. Die Einstellung gibt an ob vor der Umleitung oder erst wenn der Kunde zurückkommt vom Bezahldienst der Lagerbestand reduziert wird.',
    'FCPO_REDUCE_STOCK_BEFORE'                  => 'vor Authorisierung',
    'FCPO_REDUCE_STOCK_AFTER'                   => 'nach Authorisierung',
    'FCPO_HELP_PRESAVE_ORDER'                   => 'Die Bestellung wird schon vor der Authorisierung als unvollständige Bestellung abgespeichert. Dadurch steht die Bestellnummer auch PAYONE zur Verfügung.',
    'FCPO_VOUCHER'                              => 'Gutschein',
    'FCPO_DISCOUNT'                             => 'Rabatt',
    'FCPO_WRAPPING'                             => "Geschenkverpackung",
    'FCPO_GIFTCARD'                             => "Grußkarte",
    'FCPO_SURCHARGE'                            => 'Aufschlag',
    'FCPO_DEDUCTION'                            => 'Abschlag',
    'FCPO_SHIPPINGCOST'                         => "Versandkosten",
    'FCPO_PRODUCT_CAPTURE'                      => "Abbuchen",
    'FCPO_PRODUCTS'                             => "Artikel",
    'FCPO_PRODUCT_AMOUNT'                       => "Menge",
    'FCPO_PRODUCT_PRICE'                        => "Einzelpreis",
    'FCPO_PRODUCT_TITLE'                        => "Produkt",
    'FCPO_PRODUCT_TOTAL'                        => "Total",
    'FCPO_COMPLETE_ORDER'                       => "Bestellung abschließen",
    'FCPO_ORDERNOTCHECKED'                      => "Der Kunde hat der Bonitätprüfung nicht zugestimmt!",
    'fcpo_admin_config_status_forwarding'       => "Transaktionsstatus - Weiterleitung",
    'fcpo_admin_config_status_mapping'          => "Transaktionsstatus - Mapping",
    'fcpo_admin_config_error_mapping'           => "Fehlermeldungs - Mapping",
    'fcpo_admin_config_add'                     => "Hinzufügen",
    'fcpo_admin_config_delete'                  => "löschen",
    'fcpo_admin_config_delete_confirm'          => "Möchten Sie diesen Eintrag wirklich l&ouml;schen?",
    'fcpo_admin_config_paymenttype'             => "Zahlart",
    'fcpo_admin_config_status_payone'           => "PAYONE Status",
    'fcpo_admin_config_status_shop'             => "Shop - Status",
    'fcpo_admin_config_status'                  => "Status",
    'fcpo_admin_config_url'                     => "URL",
    'fcpo_admin_config_timeout'                 => "Timeout",
    'fcpo_status_appointed'                     => "Zahlungsvorgang initiiert (APPOINTED)",
    'fcpo_status_capture'                       => "Buchung (CAPTURE)",
    'fcpo_status_paid'                          => "Bezahlt (PAID)",
    'fcpo_status_underpaid'                     => "Unterzahlung (UNDERPAID)",
    'fcpo_status_cancelation'                   => "Rücklastschrift (CANCELATION)",
    'fcpo_status_refund'                        => "Rückerstattung (REFUND)",
    'fcpo_status_debit'                         => "Buchung (DEBIT)",
    'fcpo_status_reminder'                      => "Status des Mahnverfahrens (REMINDER)",
    'fcpo_status_vauthorization'                => "Buchung auf Abrechnungskonto (VAUTHORIZATION)",
    'fcpo_status_vsettlement'                   => "Abrechnung eines Abrechnungskontos (VSETTLEMENT)",
    'fcpo_status_transfer'                      => "Umbuchung (TRANSFER)",
    'fcpo_status_invoice'                       => "Erzeugung eines Belegs (INVOICE)",

    'FCPO_CONFIG_GROUP_CONN'             => "Verbindungs-Einstellungen",
    'FCPO_CONFIG_GROUP_GENERAL'          => "Allgemein",
    'FCPO_CONFIG_GROUP_DEBITNOTE'        => "Lastschrift",
    'FCPO_CONFIG_GROUP_CREDITCARD'       => "Kreditkarte",

    'FCPO_CONFIG_GROUP_PP_EXPRESS_LOGOS' => "PayPal",
    'FCPO_CONFIG_ADD_PP_EXPRESS_LOGO'    => "Weitere Sprache hinzuf&uuml;gen",

    'FCPO_CONFIG_DEBIT_BANKDATA'        => "Eingabe der Bankdaten",
    'FCPO_CONFIG_DEBIT_MULTISELECT'     => "Liste der unterstützten Kontolländer.<br>für Mehrfachmarkierung STRG-Taste gedrückt halten.",
    'FCPO_CONFIG_DEBIT_GER'             => "Nur bei Deutschen Konten",
    'FCPO_CONFIG_DEBIT_SHOW_OLD_FIELDS' => "zusätzlich Kontonummer/Bankleitzahl anzeigen",

    'FCPO_CONFIG_DEBIT_MANDATE'                 => "Mandatserteilung",
    'FCPO_CONFIG_DEBIT_MANDATE_TEXT'            => 'Die Mandatserteilung erfolgt mit dem kostenpflichtigen Request "managemandate".<br>Dieser Request beinhaltet einen bankaccountcheck. Allerdings ist hier keine Abfrage<br>der POS-Sperrliste möglich.',
    'FCPO_CONFIG_DEBIT_MANDATE_ACTIVE'          => "Mandatserteilung aktiv",
    'FCPO_CONFIG_DEBIT_MANDATE_DOWNLOAD'        => "Download Mandat als PDF",
    'FCPO_CONFIG_DEBIT_MANDATE_DOWNLOAD_TEXT'   => 'Diese Option kann nur ausgewählt werden, wenn bei PAYONE das Produkt<br>"SEPA-Mandate als PDF" gebucht wurde.',
    'FCPO_CONFIG_DEBIT_MANDATE_DOWNLOAD_ACTIVE' => "Download Mandat als PDF",

    'FCPO_HELP_REFPREFIX' => "Bei Requests an PAYONE muss immer eine eindeutige Referenznummer Übermittelt werden. Diese wird aus einer laufenden Nummer, normalerweise startend bei 1, generiert. Werden mit den gleichen PAYONE Account-Daten mehrere Shops betrieben ( z.B. Live- und Test-System ) kommt es zu Problemen wenn die Referenznummer schonmal verwendet wurde. Mit verschiedenen Präfixen auf den verschiedenen Systemen kann dies vermieden werden.",
    'FCPO_REFPREFIX'      => "Referenznummer Präfix ( Optional )",

    'FCPO_MANDATE_PDF'      => "SEPA Mandat-Pdf",
    'FCPO_MANDATE_DOWNLOAD' => "Download",

    'FCPO_EXPORT_CONFIG' => "Konfiguration exportieren",

    'FCPO_PAYPAL_DELADDRESS'         => 'Rechnungsadresse bei fehlender Lieferadresse als Lieferadresse &uuml;bergeben.',
    'FCPO_HELP_PAYPAL_DELADDRESS'    => 'Wird f&uuml;r den PayPal Verk&auml;uferschutz ben&ouml;tigt.',
    'FCPO_PAYPAL_LOGOS'              => 'Hier k&ouml;nnen Sie die verwendeten PayPal Express Logos hinterlegen.',
    'FCPO_PAYPAL_LOGOS_ACTIVE'       => 'Aktiv',
    'FCPO_PAYPAL_LOGOS_LANG'         => 'Sprache',
    'FCPO_PAYPAL_LOGOS_LOGO'         => 'Logo',
    'FCPO_PAYPAL_LOGOS_UPLOAD'       => 'Hochladen',
    'FCPO_PAYPAL_LOGOS_DEFAULT'      => 'Standard',
    'FCPO_PAYPAL_LOGOS_NOT_EXISTING' => 'Kein Logo vorhanden!',

    'ORDER_OVERVIEW_FCPO_ELV_BLZ'   => "BLZ",
    'ORDER_OVERVIEW_FCPO_ELV_KTONR' => "Kontonummer",
    'ORDER_OVERVIEW_FCPO_ELV_IBAN'  => "IBAN",
    'ORDER_OVERVIEW_FCPO_ELV_BIC'   => "BIC",

    'FCPO_CC_CONFIG'         => 'Feldkonfiguration',
    'FCPO_CC_STANDARD_STYLE' => 'Standardstil',
    'FCPO_CC_ERRORS'         => 'Fehlerausgabe',

    'FCPO_CC_STANDARD_INPUT'     => 'Eingabe',
    'FCPO_CC_STANDARD_SELECTION' => 'Auswahl',
    'FCPO_CC_STANDARD_FIELDS'    => 'Felder',
    'FCPO_CC_STANDARD_IFRAME'    => 'Iframe',

    'FCPO_CC_ACTIVE'   => 'Aktiv',
    'FCPO_CC_LANGUAGE' => 'Sprache',
    'FCPO_CC_SELECT'   => 'Auswahl',

    'FCPO_CC_ERRORLANG_DE'    => 'Deutsch',
    'FCPO_CC_ERRORLANG_EN'    => 'Englisch',
    'FCPO_CC_CUSTOM_TEMPLATE' => 'Benutzerdefinierte Anpassung hosted-Iframe',
    'FCPO_CC_PREVIEW'         => 'Vorschau',

    'FCPO_CREDITCARD'         => 'Karte:',
    'FCPO_NUMBER'             => 'Nummer:',
    'FCPO_CARD_SECURITY_CODE' => 'Prüfziffer:',
    'FCPO_VALID_UNTIL'        => 'Gültig bis:',
    'FCPO_FIRSTNAME'          => 'Vorname:',
    'FCPO_LASTNAME'           => 'Nachname:',

    'FCPO_PREVIEW_NOTICE' => '&Auml;nderungen sind in der Vorschau erst nach dem Speichern sichtbar!',

    'FCPO_CC_TYPE'      => "Anfragetyp",
    'FCPO_HELP_CC_TYPE' => "hosted-Iframe: Die Eingabefelder werden in einem von PAYONE gelieferten Iframe angezeigt ( PCI DSS 3.0 konform ).<br>AJAX - Die Kreditkarten-Informationen werden mittels AJAX an PAYONE gesendet.",

    'FCPO_CC_HEADER_TYPE'        => 'Typ',
    'FCPO_CC_HEADER_DIGIT_COUNT' => 'Anzahl<br>Zeichen',
    'FCPO_CC_HEADER_DIGIT_MAX'   => 'Zeichen<br>Max',
    'FCPO_CC_HEADER_IFRAME'      => 'Iframe',
    'FCPO_CC_HEADER_WIDTH'       => 'Breite',
    'FCPO_CC_HEADER_HEIGHT'      => 'H&ouml;he',
    'FCPO_CC_HEADER_STYLE'       => 'Stil',
    'FCPO_CC_HEADER_CSS'         => 'CSS',

    'FCPO_CC_ROW_CC_Number' => 'Kreditkartennummer',
    'FCPO_CC_ROW_CC_CVC'    => 'Kartenpr&uuml;fziffer',
    'FCPO_CC_ROW_CC_Month'  => 'G&uuml;ltigkeitsmonat',
    'FCPO_CC_ROW_CC_Year'   => 'G&uuml;ltigkeitsjahr',

    'FCPO_CC_TYPE_NUMERIC'  => 'Numerisch',
    'FCPO_CC_TYPE_PASSWORD' => 'Passwort',
    'FCPO_CC_TYPE_TEXT'     => 'Text',

    'FCPO_CC_IFRAME_STANDARD' => 'Standard',
    'FCPO_CC_IFRAME_CUSTOM'   => 'Benutzerdefiniert',

    'FCPO_CONFIG_GROUP_PAYOLUTION'                     => 'Payolution',
    'FCPO_PAYOLUTION_B2BMODE'                          => 'Payolution im B2B-Modus betreiben',
    'FCPO_HELP_PAYOLUTION_B2BMODE'                     => 'Bei aktiviertem B2B Modus und vom Benutzer angegebenem Firmennamen wird die USt-IdNr. abgefragt. Bei B2C Kunden wird stattdessen das Geburtsdatum abgefragt.',
    'FCPO_PAYOLUTION_COMPANY'                          => 'Firmenname',
    'FCPO_HELP_PAYOLUTION_COMPANY'                     => 'Der hier eingegebene Firmenname wird beim einblenden des Einwilligungstextes verwendet.',
    'FCPO_PAYOLUTION_MODE'                             => 'Payolution im Testmodus betreiben',
    'FCPO_PAYOLUTION_AUTH_USER'                        => 'Payolution Benutzername',
    'FCPO_HELP_PAYOLUTION_AUTH_USER'                   => 'Benutzername, der benötigt wird um Vertragsinhalte (z. B. Ratenkauf) über einen sicheren Kanalabzufragen',
    'FCPO_PAYOLUTION_AUTH_SECRET'                      => 'Payolution Passwort',
    'FCPO_HELP_PAYOLUTION_AUTH_SECRET'                 => 'Passwort, welches benötigt wird um Vertragsinhalte (z. B. Ratenkauf) über einen sicheren Kanalabzufragen.',
    'FCPO_SHOW_IBAN_FIELDS'                       => 'IBAN/BIC - Felder anzeigen',
    'FCPO_CC_USE_CVC'                                  => 'Kartenprüfziffer als Pflichtfeld abfragen',
    'fcpo_admin_config_payone_error_message'           => 'PAYONE Fehlermeldung',
    'fcpo_admin_config_status_language'                => 'Sprache',
    'fcpo_admin_config_status_own_error_message'       => 'Eigene Fehlermeldung',
    'FCPO_CONFIG_DEBIT_BIC_MANDATORY'                  => 'BIC abfragen',
    'fcpo_admin_config_error_iframe_mapping'           => 'Eigene Fehlermeldungen für Hosted iFrame',
    'fcpo_admin_config_payone_error_code'              => 'Fehlerkennung',
    'FCPO_CONFIG_GROUP_RATEPAY'                        => 'Ratepay',
    'FCPO_PROFILES_RATEPAY'                            => 'Ratepay Profile',
    'FCPO_RATEPAY_DELETE_PROFILE'                      => 'Profil löschen',
    'FCPO_RATEPAY_ADD_PROFILE'                         => 'Profil hinzufügen',
    'FCPO_PROFILES_RATEPAY_CURRENCY'                   => 'Währung',
    'FCPO_PROFILES_RATEPAY_PAYMENT'                    => 'Ratepay Zahlungsmethode',
    'FCPO_RATEPAY_PROFILE_TOGGLE_DETAILS'              => 'Konfigurationsdetails dieses Profils ein-/ausblenden',
    'FCPO_RATEPAY_PROFILE_DETAILS_FOR_ID'              => 'Profilkonfiguration für ShopID',
    'FCPO_RATEPAY_GENERAL_SETTINGS'                    => 'Ratepay Einstellungen',
    'FCPO_RATEPAY_B2BMODE'                             => 'Ratepay im B2B-Modus betreiben',
    'FCPO_HELP_RATEPAY_B2BMODE'                        => 'Bei aktiviertem B2B Modus und vom Benutzer angegebenem Firmennamen wird die USt-IdNr. abgefragt. Bei B2C Kunden wird stattdessen das Geburtsdatum abgefragt.',
    'FCPO_CONFIG_GROUP_AMAZONPAY'                      => 'AmazonPay',
    'FCPO_AMAZONPAY_SELLERID'                          => 'Amazon Seller-ID',
    'FCPO_AMAZONPAY_CLIENTID'                          => 'Amazon Client-ID',
    'FCPO_AMAZONPAY_GET_CONFIG'                        => 'Amazon-Konfiguration von PAYONE abrufen',
    'FCPO_AMAZONPAY_ERROR_GETTING_CONFIG'              => 'Es gab ein Problem beim Abrufen der AmazonPay-Konfigurationseinstellungen. Nähere Infos finden Sie im Admin unter PAYONE Protokolle/Logs->API Logs.',
    'FCPO_AMAZONPAY_SUCCESS_GETTING_CONFIG'            => 'Die AmazonPay-Konfiguration wurde erfolgreich abgerufen',
    'FCPO_AMAZONPAY_BUTTON_TYPE'                       => 'Amazon Button Typ',
    'FCPO_AMAZONPAY_BUTTON_TYPE_PwA'                   => 'Amazon Pay (Standard)',
    'FCPO_AMAZONPAY_BUTTON_TYPE_Pay'                   => 'Pay (Etwas kleiner)',
    'FCPO_AMAZONPAY_BUTTON_TYPE_A'                     => 'Amazon Logo (Klein)',
    'FCPO_AMAZONPAY_BUTTON_COLOR'                      => 'Amazon Button Farbe',
    'FCPO_AMAZONPAY_BUTTON_COLOR_GOLD'                 => 'Gold (standard)',
    'FCPO_AMAZONPAY_BUTTON_TYPE_LIGHT_GRAY'            => 'Hellgrau',
    'FCPO_AMAZONPAY_BUTTON_TYPE_DARKGRAY'              => 'Dunkelgrau',
    'FCPO_AMAZONPAY_BUTTON_LANG'                       => 'Sprache des Amazon Buttons',
    'FCPO_AMAZONPAY_BUTTON_LANG_NONE'                  => 'Automatisch',
    'FCPO_AMAZONPAY_BUTTON_LANG_ENGLISH_UK'            => 'Englisch (Großbritannien)',
    'FCPO_AMAZONPAY_BUTTON_LANG_GERMAN_GERMANY'        => 'Deutsch (Deutschland)',
    'FCPO_AMAZONPAY_BUTTON_LANG_FRENCH_FRANCE'         => 'Französisch (Frankreich)',
    'FCPO_AMAZONPAY_BUTTON_LANG_ITALIAN_ITALY'         => 'Italienisch (Italien)',
    'FCPO_AMAZONPAY_BUTTON_LANG_SPANISH_SPAIN'         => 'Spanisch (Spanien)',
    'FCPO_AMAZONPAY_MODE'                              => 'Amazon-Modus',
    'FCPO_AMAZONPAY_MODE_ALWAYSSYNC'                   => 'Immer Synchron',
    'FCPO_AMAZONPAY_MODE_FIRSTSYNCTHENSYNC'            => 'Erst Synchron, dann Asynchron versuchen',
    'FCPO_AMAZONPAY_LOGINMODE'                         => 'Loginmethode',
    'FCPO_AMAZONPAY_LOGINMODE_AUTO'                    => 'Automatisch (Bei SSL "Popup" und ohne "Redirect")',
    'FCPO_AMAZONPAY_LOGINMODE_POPUP'                   => 'Popup (Funktioniert nur mit SSL)',
    'FCPO_AMAZONPAY_LOGINMODE_REDIRECT'                => 'Redirect',
    'FCPO_CONFIG_GROUP_SECINVOICE'                     => 'Gesicherter Rechnungskauf (rec/POV)',
    'FCPO_CONFIG_GROUP_BNPL'                           => 'BNPL Zahlarten (fnc/PIV, fnc/PIN)',
    'FCPO_SECINVOICE_PORTAL_ID'                        => 'PAYONE Portal ID (für Zahlart Gesicherter Rechnungskauf)',
    'FCPO_BNPL_PORTAL_ID'                              => 'PAYONE Portal ID (für Zahlart BNPL)',
    'FCPO_SECINVOICE_PORTAL_KEY'                       => 'PAYONE Portal Key (für Zahlart Gesicherter Rechnungskauf)',
    'FCPO_BNPL_PORTAL_KEY'                             => 'PAYONE Portal Key (für Zahlart BNPL)',
    'FCPO_BNPL_ALLOW_DIFF_ADDRESS'                     => 'Abweichende Lieferadresse zulassen',
    'FCPO_BNPL_ADMIN_DEBIT_REASON_TITLE'               => 'Stornierungsgrund',
    'FCPO_BNPL_CANCELLATION_REASON_CRQ'                => 'Der Verbraucher hat eine Stornierung der Bestellung beantragt',
    'FCPO_BNPL_CANCELLATION_REASON_DUP'                => 'Die Bestellung wurde versehentlich zweimal erstellt',
    'FCPO_BNPL_CANCELLATION_REASON_FRD'                => 'Der Verbraucher entpuppte sich als Betrüger',
    'FCPO_BNPL_CANCELLATION_REASON_UND'                => 'Der Händler kann die Bestellung nicht ausführen',
    'FCPO_GROUP_LOGGING'                               => 'Protokollierung',
    'FCPO_TRANSACTIONREDIRECTLOGGING_NONE'             => 'Keine Protokollierung (Standard)',
    'FCPO_TRANSACTIONREDIRECTLOGGING_ALL'              => 'Alles protokollieren',
    'FCPO_TRANSACTIONREDIRECTLOGGING'                  => 'Protokollieren der Weiterleitung von Transaktionsstatusmeldungen',
    'FCPO_HELP_TRANSACTIONREDIRECTLOGGING'             => 'Hier können Sie die Protokollierung von Transaktionsstatusweiterleitungen aktivieren. Entsprechende Aktivitäten landen dann in der Datei <i>fcpo_message_forwarding.log</i> im Logverzeichnis des Shops. Die Protokollierung sollte nicht dauerhaft aktiviert werden, da dies große Logdateien erzeugt',
    'FCPO_HASH_METHOD'                                 => 'Key-Verschlüsselungsverfahren',
    'FCPO_HELP_HASH_METHOD'                            => 'Hier können Sie einstellen, welches Key-Verschlüsselungsverfahren zur Kommunikation mit der Payone-API verwendet wird. Wenn möglich, wird die Verwendung von sha2-384 empfohlen.',
    'FCPO_EMAIL_CLEARING_SUBJECT'                      => 'Ihre Überweisungsdaten zur Bestellnummer',
    'FCPO_EMAIL_CLEARING_BODY_WELCOME'                 => "Hallo %NAME% %SURNAME%,\nzur Begleichung der Rechnung verwenden Sie bitte folgende Daten zur Überweisung:\n\n",
    'FCPO_EMAIL_BANK'                                  => 'Bankname',
    'FCPO_EMAIL_ROUTINGNUMBER'                         => 'BLZ',
    'FCPO_EMAIL_ACCOUNTNUMBER'                         => 'Kto.Nr.',
    'FCPO_EMAIL_BIC'                                   => 'BIC',
    'FCPO_EMAIL_IBAN'                                  => 'IBAN',
    'FCPO_EMAIL_CLEARING_BODY_THANKYOU'                => 'Vielen Dank, dein %SHOPNAME%-Team',
    'FCPO_EMAIL_USAGE'                                 => 'Verwendungszweck',
    'FCPO_TRANSACTIONREDIRECTMETHOD_DIRECT'            => 'Direkte Weiterleitung (Standard)',
    'FCPO_TRANSACTIONREDIRECTMETHOD_CRONJOB'           => 'Verzögert mit Cronjob (Übertragungssicherheit)',
    'FCPO_HELP_TRANSACTIONREDIRECTMETHOD'              => 'Wählen Sie die Methode wie Transaktionsstatusmeldungen weitergeleitet werden. Ihnen stehen zur Auswahl:<br><b>Direkte Weiterleitung:</b><br>Bei der direkten Weiterleitung wird die Statusmeldung direkt an die konfigurierten Ziele weitergeleitet. Sie bietet eine hohe Weiterleitungsgeschwindigkeit und eine moderate Übertragungssicherheit.<br><b>Verzögert mit Cronjob:</b><br>Diese Methode leitet die Statusmeldung nicht direkt weiter, sondern sammelt die eingehenden Aufrufe und leitet diese erst durch einen Cronjobaufruf an die Ziele weiter. Diese Methode bietet vor allem eine hohe Übertragungssicherheit. Die Weiterleitungsgeschwindigkeit hängt von der Serverkonfiguration ab. Bitte konsultieren Sie das <a href="">Handbuch</a> um zu erfahren wie Sie diesen Modus effizient einrichten',
    'FCPO_TRANSACTIONREDIRECTMETHOD'                   => 'Weiterleitungsmethode',
    'FCPO_TRANSACTION_TIMEOUT'                         => 'Zeitlimit in Sekunden',
    'FCPO_HELP_TRANSACTIONREDIRECT_TIMEOUT'            => 'Um eine unterbrechungsfreie Weiterleitung zu ermöglichen werden Statusmeldungen mit einem Zeitlimit versendet. Abhängig von ihrem Serversetup kann es notwendig sein, dass Sie einen höheren Wert als die Voreingstellten 10s benötigen.',
    'FCPO_FORWARD_REDIRECTS'                           => 'Transaktionsstatusweiterleitungen',
    'FCPO_FORWARD_REDIRECT_TARGETURL'                  => 'Zieladresse',
    'FCPO_FORWARD_REDIRECT_TRIES'                      => 'Aufrufversuche',
    'FCPO_FORWARD_REDIRECT_LASTTRY'                    => 'Zuletzt versucht',
    'FCPO_FORWARD_REDIRECT_FULFILLED'                  => 'Erfolg',
    'FCPO_FORWARD_REDIRECT_FULFILLED_YES'              => 'Ja',
    'FCPO_FORWARD_REDIRECT_FULFILLED_NO'               => 'Nein',
    'FCPO_FORWARD_REDIRECT_DETAILS'                    => 'Details',
    'FCPO_FORWARD_REDIRECT_TRIGGER'                    => 'Alle fehlenden/nicht erfüllten Aufrufe auslösen',

    'FCPO_CONFIG_GROUP_APPLE_PAY'                      => "Apple Pay",
    'FCPO_HELP_APPLE_PAY_MERCHANT_ID'                  => "Merchant ID",
    'FCPO_APPLE_PAY_MERCHANT_ID'                       => "Merchant ID",
    'FCPO_HELP_APPLE_PAY_CERTIFICATE'                  => "Der Name des Zertifikats wird dem Textfeld entnommen . Es kann in jeden gewünschten Namen geändert werden. Wenn beim Speichern der hochgeladenen Datei leer ist, wird standardmäßig der ursprüngliche Name der Datei verwendet.<br/>Das Textfeld kann auch verwendet werden, um eine vorhandene Zertifikatsdatei auf dem Server zu benennen, ohne eine neue Datei hochzuladen.",
    'FCPO_APPLE_PAY_CERTIFICATE'                       => "Händleridentifikationszertifikat",
    'FCPO_APPLE_PAY_CONFIG_CERTIFICATE_MISSING'        => "Die aktuell konfigurierte Zertifikatsdatei existiert nicht.<br/>Apple Pay kann nicht als Zahlungsmethode verwendet werden.",
    'FCPO_HELP_APPLE_PAY_KEY'                          => "Dies ist ein Mehrfachfeld. Sie können eine Datei mit dem Schlüssel hochladen, oder den Inhalt des Schlüssels direkt in das Textfeld unten eingeben. Priorität hat die hochgeladene Datei, wenn beide Optionen verwendet werden!<br/><br/>
Das kleinere Textfeld wird verwendet, um die Zieldatei oder den Pfad zu einer vorhandenen Schlüsseldatei auf dem Server zu benennen.<br/>
- Wenn beim Speichern der hochgeladenen Datei leer, wird der ursprüngliche Name der hochgeladenen Datei verwendet.<br/>
- Wenn beim Speichern der Direkteingabe leer, wird der Standardname 'merchant_id.key' verwendet.<br/>
- Wenn leer, während keines davon ausgeführt wird, wird ein leerer Wert angenommen.",
    'FCPO_APPLE_PAY_KEY'                               => "Privater Schlüssel des Zertifikats",
    'FCPO_HELP_APPLE_PAY_PASSWORD'                     => "Passwort für Zertifikatsschlüssel",
    'FCPO_APPLE_PAY_PASSWORD'                          => "Passwort für Zertifikatsschlüssel",
    'FCPO_APPLE_PAY_CREDITCARD'                        => "Erlaubte Kreditkarten",
    'FCPO_APPLE_PAY_CREATE_SESSION_ERROR'              => "Fehler beim Herstellen der Verbindung zum Apple Pay Service.",
    'FCPO_APPLE_PAY_CREATE_SESSION_ERROR_CARDS'        => "In der Konfiguration ist kein gültiger Kreditkartentyp zulässig. Die Apple Pay-Sitzung kann nicht initialisiert werden.",

    'FCPO_SHADOW_BASKET'                               => 'Schatten-Warenkorb',
    'FCPO_POSSIBLE_FRAUD_DETECTED'                     => 'Ein möglicher Betrugsversuch wurde entdeckt. Bitte prüfen Sie diesen Warenkorb gegen die Bestellung.',
    'FCPO_GENERAL_SHADOWBASKET_BRUTTO'                 => 'Bruttosumme des Prüfwarenkorbs',
    'FCPO_GENERAL_SHADOWBASKET_NETTO'                  => 'Nettosumme des Prüfwarenkorbs',

    'PAYONE Alipay' => 'PAYONE Alipay',
    'PAYONE Amazon Pay' => 'PAYONE Amazon Pay',
    'PAYONE Apple Pay' => 'PAYONE Apple Pay',
    'PAYONE Bancontact' => 'PAYONE Bancontact',
    'PAYONE Barzahlen' => 'PAYONE Barzahlen',
    'PAYONE eps Überweisung' => 'PAYONE eps Überweisung',
    'PAYONE Gesicherter Rechnungskauf' => 'PAYONE Gesicherter Rechnungskauf',
    'PAYONE Gesicherter Rechnungskauf (neu)' => 'PAYONE Gesicherter Rechnungskauf (neu)',
    'PAYONE Gesicherter Ratenkauf' => 'PAYONE Gesicherter Ratenkauf',
    'PAYONE Gesicherte Lastschrift' => 'PAYONE Gesicherte Lastschrift',
    'PAYONE Giropay' => 'PAYONE Giropay',
    'PAYONE iDEAL' => 'PAYONE iDEAL',
    'PAYONE Klarna Ratenkauf' => 'PAYONE Klarna Ratenkauf',
    'PAYONE Klarna Rechnung' => 'PAYONE Klarna Rechnung',
    'PAYONE Klarna Sofort bezahlen' => 'PAYONE Klarna Sofort bezahlen',
    'PAYONE Kreditkarte' => 'PAYONE Kreditkarte',
    'PAYONE Lastschrift' => 'PAYONE Lastschrift',
    'PAYONE Nachnahme' => 'PAYONE Nachnahme',
    'PAYONE paydirekt' => 'PAYONE paydirekt',
    'PAYONE PayPal Express' => 'PAYONE PayPal Express',
    'PAYONE PayPal' => 'PAYONE PayPal',
    'PAYONE PostFinance Card' => 'PAYONE PostFinance Card',
    'PAYONE PostFinance E-Finance' => 'PAYONE PostFinance E-Finance',
    'PAYONE Przelewy24' => 'PAYONE Przelewy24',
    'PAYONE Ratepay Rechnungskauf' => 'PAYONE Ratepay Rechnungskauf',
    'PAYONE Ratepay Lastschrift' => 'PAYONE Ratepay Lastschrift',
    'PAYONE Ratepay Ratenkauf' => 'PAYONE Ratepay Ratenkauf',
    'PAYONE Rechnungskauf' => 'PAYONE Rechnungskauf',
    'PAYONE Sofort Überweisung' => 'PAYONE Sofort Überweisung',
    'PAYONE Trustly' => 'PAYONE Trustly',
    'PAYONE Unzer Lastschrift' => 'PAYONE Unzer Lastschrift',
    'PAYONE Unzer Ratenkauf' => 'PAYONE Unzer Ratenkauf',
    'PAYONE Unzer Rechnungskauf' => 'PAYONE Unzer Rechnungskauf',
    'PAYONE Vorkasse' => 'PAYONE Vorkasse',
    'PAYONE WeChat Pay' => 'PAYONE WeChat Pay',
    'FCPO_KLARNA' => 'PAYONE Klarna Payments',
);

/*
[{ oxmultilang ident="GENERAL_YOUWANTTODELETE" }]
*/
